export type BoxSizing = "border" | "content";
export type Display =
  | "block"
  | "hidden"
  | "flex"
  | "grid"
  | "inline"
  | "inline-block"
  | "inline-flex"
  | "inline-grid"
  | "flow-root"
  | "table"
  | "table-caption"
  | "table-cell"
  | "table-column"
  | "table-column-group"
  | "table-footer-group"
  | "table-header-group"
  | "table-row-group"
  | "table-row"
  | "contents";
export type Float = "left" | "right" | "none";
export type Clear = "left" | "right" | "both" | "none";
export type ObjectFit = "contain" | "cover" | "fill" | "none" | "scale-down";
export type ObjectPosition =
  | "bottom"
  | "center"
  | "left"
  | "left-bottom"
  | "left-top"
  | "right"
  | "right-bottom"
  | "right-top"
  | "top";
export type Overflow = "auto" | "hidden" | "visible" | "scroll";
export type Overscroll = "auto" | "contain" | "none";
export type Position = "static" | "fixed" | "absolute" | "relative" | "sticky";
export type ZIndex = "0" | "10" | "20" | "30" | "40" | "50" | "auto";
export type TailwindSpaces =
  | "auto"
  | "px"
  | "0"
  | "0.5"
  | "1"
  | "2"
  | "3"
  | "4"
  | "5"
  | "6"
  | "8"
  | "10"
  | "12"
  | "16"
  | "20"
  | "24"
  | "32"
  | "40"
  | "48"
  | "56"
  | "64"
  | "72"
  | "80"
  | "96"
  | "1/2"
  | "1/3"
  | "2/3"
  | "1/4"
  | "2/4"
  | "3/4"
  | "full"
  | "-px"
  | "-0.5"
  | "-1"
  | "-2"
  | "-3"
  | "-4"
  | "-5"
  | "-6"
  | "-8"
  | "-10"
  | "-12"
  | "-16"
  | "-20"
  | "-24"
  | "-32"
  | "-40"
  | "-48"
  | "-56"
  | "-64"
  | "-72"
  | "-80"
  | "-96"
  | "-1/2"
  | "-1/3"
  | "-2/3"
  | "-1/4"
  | "-2/4"
  | "-3/4"
  | "-full";
